// <auto-generated />
namespace MvcAppSearch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DRdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DRdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201311051933221_DRdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
